require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe IpValuesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # IpValue. As you add validations to IpValue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IpValuesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ip_values as @ip_values" do
      ip_value = IpValue.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:ip_values)).to eq([ip_value])
    end
  end

  describe "GET #show" do
    it "assigns the requested ip_value as @ip_value" do
      ip_value = IpValue.create! valid_attributes
      get :show, params: {id: ip_value.to_param}, session: valid_session
      expect(assigns(:ip_value)).to eq(ip_value)
    end
  end

  describe "GET #new" do
    it "assigns a new ip_value as @ip_value" do
      get :new, params: {}, session: valid_session
      expect(assigns(:ip_value)).to be_a_new(IpValue)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ip_value as @ip_value" do
      ip_value = IpValue.create! valid_attributes
      get :edit, params: {id: ip_value.to_param}, session: valid_session
      expect(assigns(:ip_value)).to eq(ip_value)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new IpValue" do
        expect {
          post :create, params: {ip_value: valid_attributes}, session: valid_session
        }.to change(IpValue, :count).by(1)
      end

      it "assigns a newly created ip_value as @ip_value" do
        post :create, params: {ip_value: valid_attributes}, session: valid_session
        expect(assigns(:ip_value)).to be_a(IpValue)
        expect(assigns(:ip_value)).to be_persisted
      end

      it "redirects to the created ip_value" do
        post :create, params: {ip_value: valid_attributes}, session: valid_session
        expect(response).to redirect_to(IpValue.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ip_value as @ip_value" do
        post :create, params: {ip_value: invalid_attributes}, session: valid_session
        expect(assigns(:ip_value)).to be_a_new(IpValue)
      end

      it "re-renders the 'new' template" do
        post :create, params: {ip_value: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ip_value" do
        ip_value = IpValue.create! valid_attributes
        put :update, params: {id: ip_value.to_param, ip_value: new_attributes}, session: valid_session
        ip_value.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ip_value as @ip_value" do
        ip_value = IpValue.create! valid_attributes
        put :update, params: {id: ip_value.to_param, ip_value: valid_attributes}, session: valid_session
        expect(assigns(:ip_value)).to eq(ip_value)
      end

      it "redirects to the ip_value" do
        ip_value = IpValue.create! valid_attributes
        put :update, params: {id: ip_value.to_param, ip_value: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ip_value)
      end
    end

    context "with invalid params" do
      it "assigns the ip_value as @ip_value" do
        ip_value = IpValue.create! valid_attributes
        put :update, params: {id: ip_value.to_param, ip_value: invalid_attributes}, session: valid_session
        expect(assigns(:ip_value)).to eq(ip_value)
      end

      it "re-renders the 'edit' template" do
        ip_value = IpValue.create! valid_attributes
        put :update, params: {id: ip_value.to_param, ip_value: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ip_value" do
      ip_value = IpValue.create! valid_attributes
      expect {
        delete :destroy, params: {id: ip_value.to_param}, session: valid_session
      }.to change(IpValue, :count).by(-1)
    end

    it "redirects to the ip_values list" do
      ip_value = IpValue.create! valid_attributes
      delete :destroy, params: {id: ip_value.to_param}, session: valid_session
      expect(response).to redirect_to(ip_values_url)
    end
  end

end
